### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by espizo**

### CODE REVIEW

**Comment by fiftysoft** [comment]
@espizo thanks for your pull request are you test it at docker and worked ?

**Comment by espizo** [comment]
Hi!

Seems to work fine for me with a remote nginx-rtmp server!

If you have docker yourself, then it should be fairly easy to verify with the `docker-compose up` command :)

Nice work on this repo, btw!

**Comment by fiftysoft** [comment]
@espizo why you not use " git clone [repo-url] " at docker file  i think it well be better i'm right ?

**Comment by espizo** [comment]
@fiftysoft that would be a very atypical use of docker and it would involve a lot of issues setting up ssh keys for git inside docker, etc.

The normal workflow for docker-enabled git repos is:
```
$ git clone <repo url>
$ docker-compose up    # or docker build ... && docker run ...

**Comment by fiftysoft** [comment]
@espizo thanks for your good work

**Pull request merged**
